### ISSUE TITLE
Small mistakes 

### ISSUE THREAD

**Issue by usser1976** [SuperStulle007/UltraCapes#1]
Hello, small mistakes are in there.  In fire and turtle no cape appears.  With a pickaxe you fly from the server (line 104) think the white background is in the png, it must be transparent 🤔 If you click on the cape remove butts press error (line 189)

Mein Deutsch ist besser 😂

**Comment by SuperStulle007** [comment]
Alles außer Cape Remove sollte gefixxt sein ^^
Everything except cape remove should be fixed.

**Comment by usser1976** [comment]
Das ist mal fixer fix 😂 thx
