### ISSUE TITLE
Discord, more capes

### ISSUE THREAD

**Issue by PetyXbron** [SuperStulle007/UltraCapes#16]
Hey! 
I know this is not issue, but can I ask?

# "@SuperStulle007#7777" isn't working :(
I wanted to ask you with discord but... I can't find you :/

# How can I add more capes?
I know, I just need to find some capes on internet, but can you recommend some website where can I find this .png format capes? :) thanks

_also, I want say, This is very cool plugin and I love it_
There's one cape:
![minecraft-capes-png-4](https://user-images.githubusercontent.com/35902119/83194187-8af87280-a138-11ea-9fa2-a0b21703180c.png)
Do plugin support it? 
Waiting for your reply, thanks :)

**Comment by 5oC8** [comment]
Hi can someone send me that plugin i will be happy and ya there is no download link

**Comment by PetyXbron** [comment]
> Hi can someone send me that plugin i will be happy and ya there is no download link

there is it
https://poggit.pmmp.io/ci/SuperStulle007/UltraCapes/

**Comment by 5oC8** [comment]
Very Very thanks bro maan :)

**Comment by 5oC8** [comment]
but is that for java edition?

**Comment by PetyXbron** [comment]
> but is that for java edition?

Off course not. This is for Bedrock pocketmine.

**Comment by 5oC8** [comment]
ok

**Comment by 5oC8** [comment]
thx
