### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by BogdanMakarchuk** [SuperStulle007/UltraCapes#2]
Do save the cloak after a restart on the server or after a restart

**Comment by SuperStulle007** [comment]
The Capes are saved in the plugins_data/UltraCapes folder after every restart.

**Comment by BogdanMakarchuk** [comment]
After a restart to the server, the player does not save the cape

**Comment by BogdanMakarchuk** [comment]
I would like to see if a player chooses a cape, then after re-entering the server, she will be on it

**Comment by dearminder** [comment]
it still dont saving
