### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by GamerMJay** [SuperStulle007/UltraCapes#26]
Hey ich habe einen Bug im plugin gefunden wäre nett wenn du es fixen könnest
 
![Screenshot_2021-10-25-18-26-20-16_3686cb59f45a8f4a2b1e8d6e99664d6d](https://user-images.githubusercontent.com/66413999/138734115-ab2aa983-947b-4537-bafb-8cb1545f53ac.jpg)

**Comment by SuperStulle007** [comment]
Du musst die GD Extension auf deinem Server hinzufüen,

**Comment by GamerMJay** [comment]
Ah Okay danke
