### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by deuhd** [SuperStulle007/UltraCapes#4]
CRITICAL Error: "Call to undefined function SuperStulle007\UltraCapes\imagecreatefrompng()" (EXCEPTION) in "plugins/UltraCapes-master/src/SuperStulle007/UltraCapes/Main" at line 60

**Comment by SuperStulle007** [comment]
You have to enable GD.

**Comment by deuhd** [comment]
Yes but on my host has no bin file
