### ISSUE TITLE
Cape Remove

### ISSUE THREAD

**Issue by SilverzPlayz** [SuperStulle007/UltraCapes#4]
When I do /cape and select Remove Cape when a cape is activated it crashes saying "Internal Server Error" same thing if i do /cape remove

Server thread/DEBUG]: #0 plugins/UltraCapes_dev-14.phar/src/UltraCapes/Main(189): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[29] Undefined index: SilverzPlayz, string[76] phar:///home/gs-41736/plugins/UltraCapes_dev-14.phar/src/UltraCapes/Main.php, integer 189, array[6])

**Comment by SuperStulle007** [comment]
Jep I'll fix that

**Comment by SilverzPlayz** [comment]
thanks

**Comment by SuperStulle007** [comment]
Please try the latest build.

**Comment by usser1976** [comment]
I'm sorry, the cape remains at the cape remove. 🤔

**Comment by SuperStulle007** [comment]
Besser als ein Error 😂

**Comment by usser1976** [comment]
Auf jeden fall 😃

**Comment by SuperStulle007** [comment]
Please test the new Build.

**Comment by usser1976** [comment]
Server thread/CRITICAL]: TypeError: "Argument 2 passed to pocketmine\entity\Skin::__construct() must be of the type string, null given, called in phar:///home/minecraft/plugins/UltraCapes_dev-22.phar/src/UltraCapes/Main.php on line 189" (EXCEPTION) in "src/pocketmine/entity/Skin" at line 50

**Comment by usser1976** [comment]
Tut mir echt leid 🤔 
Kommt beim removen

**Comment by Baducai** [comment]
Wie heisst du auf Discord @SuperStulle007

**Comment by SuperStulle007** [comment]
My Discordname: @->("SυρҽɾSƚυʅʅҽ007")#4539

**Comment by DenielWorld** [comment]
@SilverzPlayz weren't you a "dev"? Should of fixed it yourself lmao.

**Comment by usser1976** [comment]
Cape Remove works great now.  The problem with no cape tortoise, fire and pickaxe is back 😂
Ich glaube du hasst mich langsam 😉 discord geht nicht zu adden 🤔
