### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by darkadams** [SuperStulle007/UltraCapes#5]
When u try to remove ur Cape it crashes the server and also In the future maybe you can add prices for capes so people can buy them when they do /Cape. anyways I love this plugin

**Comment by SuperStulle007** [comment]
You can sell the permissions for a cape with another plugin.

**Comment by darkadams** [comment]
What plugin might that be ?

**Comment by SuperStulle007** [comment]
Maybe you can sell Ranks with that Permission

(https://poggit.pmmp.io/ci/zZPROGAMERZz423/RankShopSystem/RankShopSystem) 

For that you need PurePerms.


Or i think there is a plugin, that let you sell single permissions.

**Comment by darkadams** [comment]
Thx
